package io.alapierre.jackson;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * @author Adrian Lapierre {@literal al@alapierre.io}
 * Copyrights by original author 17.11.2024
 */
@JsonIgnoreProperties(
        value = "docType", // ignore manually set docType, it will be automatically generated by Jackson during serialization
        allowSetters = true // allows the docType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "docType", visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = SalesInvoiceCreateDto.class, name = "FS"),
        @JsonSubTypes.Type(value = CurrencyInvoiceCreateDto.class, name = "FW")
})
public interface CreateInvoiceRequest {
}
